### PR TITLE
chore: Add an issue form for event proposals

### PR DESCRIPTION
**Pull request by ditsuke**
## What
Issue form for event proposals; links to our Discord, Telegram and membership form in the issue template chooser.

### Screenshots

- Template chooser
  image

- Proposal form
  image

### FAQ

> How do I test this?

Try making a new issue on my fork https://github.com/ditsuke/logistics-and-event-contributions. Since my `master` branch contains the changes from this PR, you'll be able to see the selector and issue form.

### CODE REVIEW

**Comment by achintya-7** [comment]
I only faced one issue that was related to telegram link. I believe this is an issue from my own device.
Otherwise, all other features are working properly.
I approve

**Comment by achintya-7** [comment]
> I only faced one issue that was related to telegram link. I believe this is an issue from my own device.
> Otherwise, all other features are working properly.
> I approve 

Nope its alright. All features are working.
Its just big tech trying to silence us down.

**Comment by ditsuke** [comment]
@achintya-7 check again and approve by reviewing ^^ 
image

**Comment by achintya-7** [comment]
@ditsuke
Everything is working as intended.
I approve.

**Review by achintya-7 — APPROVED** [review]
working fine and dandy

**Pull request merged**
