### PR TITLE
Added ALiAS graphics

### PR DESCRIPTION
**Pull request by jailbreakerVC**

### CODE REVIEW

**Comment by ditsuke** [comment]
Can you fit these under events? See https://github.com/asetalias/Logistics-and-Event-Contributions/tree/60898a1f4e041474be62db8c69b360829f4d7f3a/Events/2017-18

**Comment by jailbreakerVC** [comment]
oh okay

**Comment by jailbreakerVC** [comment]
@ditsuke is it alright now?

**Comment by ditsuke** [comment]
Almost! Can we have Hacktoberfest ones in `<year>/Oct-29-Hacktoberfest`?

I think the year might be `2022-2023` :stuck_out_tongue:

**Comment by jailbreakerVC** [comment]
omg :sob:

**Comment by jailbreakerVC** [comment]
@ditsuke done

**Review by ditsuke — COMMENTED** [review]
LGTM

**Review by ditsuke — APPROVED** [review]
LGTM

**Comment by ditsuke** [comment]
Thanks @jailbreakerVC

**Pull request merged**
